---
iip_jdbc_connection:
  name: "MAS_Identity-IIP"
  owner: "7layer"
  group: "7layer"
  ssl_port: 9443
  file:
    src: "roles/mas_identity/files/iip_jdbc_connection.j2"
    dest: '/var/tmp/mas_identity_iip_jdbc_connection.xml'
  api_url: '/restman/1.0/jdbcConnections'
  id_xml_tag: 'l7:Id'
  id_regex: 's,.*<l7:Id>\([^<]*\)</l7:Id>.*,\1,g'
  curl_log: '/var/tmp/restman_mas_identity_iip_jdbc_connection.log'
mas_cassandra_connection:
  name: "MAS_Identity-MAS"
  owner: "layer7"
  group: "layer7"
  ssl_port: 9443
  file:
    src: "roles/mas_identity/files/mas_cassandra_connection.j2"
    dest: '/var/tmp/mas_identity_cassandra_connection.xml'
  api_url: '/restman/1.0/cassandraConnections'
  id_xml_tag: 'l7:Id'
  id_regex: 's,.*<l7:Id>\([^<]*\)</l7:Id>.*,\1,g'
  curl_log: '/var/tmp/restman_mas_identity_mas_cassandra_connection.log'
