---
- hosts: mysql_databases
  vars_files:
    - group_vars/mysql.yml
    - group_vars/gateway.yml
    - group_vars/cassandra.yml
    - group_vars/otk.yml
  roles:
    - mysql
- hosts: cassandra_databases
  vars_files:
    - group_vars/mysql.yml
    - group_vars/gateway.yml
    - group_vars/cassandra.yml
    - group_vars/otk.yml
  roles:
    - cassandra
- hosts: gateways
  vars_files:
    - group_vars/mysql.yml
    - group_vars/gateway.yml
    - group_vars/cassandra.yml
    - group_vars/otk.yml
  roles:
    - common
    - gateway
    - otk
    - otk_schema_data
    - restart_services
