---
- hosts: mysql_databases
  vars_files:
    - group_vars/mysql.yml
    - group_vars/gateway.yml
  roles:
    - mysql
- hosts: gateways
  vars_files:
    - group_vars/mysql.yml
    - group_vars/gateway.yml
  roles:
    - common
    - gateway
