---
cassandra_connection:
  name: "MAS_Storage"
  owner: "layer7"
  group: "layer7"
  ssl_port: 9443
  file:
    src: "roles/mas_storage/files/cassandra_connection.j2"
    dest: '/var/tmp/mas_storage_cassandra_connection.xml'
  api_url: '/restman/1.0/cassandraConnections'
  id_xml_tag: 'l7:Id'
  id_regex: 's,.*<l7:Id>\([^<]*\)</l7:Id>.*,\1,g'
  curl_log: '/var/tmp/restman_cassandra_connection.log'
