---
## database.yml
## the OAuth toolkit playbook needs to be run before these schema updates if you are using the same MAG
## database and user credentials
- name: create the MAG database schema
  mysql_db: name={{ mag_database.schema }}
          state=present
          login_host={{ login_host }}
          login_port={{ mag_database.port }}
          login_user={{ mag_database.admin.user }}
          login_password={{ mag_database.admin.pass }}

- name: create the MAG user
  mysql_user: name={{ mag_database.user }}
            host={{ item }}
            priv={{ mag_database.schema }}.*:ALL
            password={{ mag_database.pass }}
            login_host={{ login_host }}
            login_port={{ mag_database.port }}
            login_user={{ mag_database.admin.user }}
            login_password={{ mag_database.admin.pass }}
  with_items:
    - 127.0.0.1
    - ::1
    - "%"
    - localhost

- name: seed the MAG database OTK DB test data
  mysql_db: name={{ mag_database.schema }}
          state=import
          target={{ item.dest }}
          login_host={{ login_host }}
          login_port={{ mag_database.port }}
          login_user={{ mag_database.admin.user }}
          login_password={{ mag_database.admin.pass }}
  with_items:
    - "{{ mag_database_files.sql.mag_db_schema }}"
    - "{{ mag_database_files.sql.mag_db_testdata }}"
    - "{{ mag_database_files.sql.mag_otk_db_data }}"
    - "{{ mag_database_files.sql.mag_otk_db_testdata }}"
