---
## auto_provision.yml
- name: create the auto-provision directory
  file: path=/opt/SecureSpan/Gateway/node/default/etc/bootstrap/services owner={{ license.owner }} group={{ license.group }} mode=755 state=directory

- name: create the auto-provision file for Gateway Management Service
  file: path=/opt/SecureSpan/Gateway/node/default/etc/bootstrap/services/wsman owner={{ license.owner }} group={{ license.group }} mode=644 state=touch

- name: create the auto-provision file for Gateway REST Management Service
  file: path=/opt/SecureSpan/Gateway/node/default/etc/bootstrap/services/restman owner={{ license.owner }} group={{ license.group }} mode=644 state=touch

