---
## headless.yml
# only provision the gateway when you are ready to set the cluster name of
# the node
- name: dynamically create the headless config file
  template: src={{ headless.file.src }} dest={{ headless.file.dest }} owner={{ headless.owner }} group={{ headless.group }} mode={{ headless.mode }}

- name: configure the gateway via headless option
  command: bash -c "/bin/cat {{ headless.file.dest }} | /usr/bin/sudo -u {{ headless.sudo.username }} /opt/SecureSpan/Appliance/libexec/ssgconfig_launch headless appliance-full >> /var/tmp/config_gateway.log 2>&1"

- name: sleep for {{ headless.sleep }} seconds to allow SSG to start and wait for {{ cluster.ssl_port }}
  #wait_for: port={{ trusted_certificate.ssl_port }} delay={{ headless.sleep }}
  wait_for: port={{ cluster.ssl_port }} delay={{ headless.sleep }}

- name: wait for "{{ headless.log_file_regex }}" to appear in {{ headless.log_file }}
  #wait_for: port={{ trusted_certificate.ssl_port }} delay={{ headless.sleep }}
  wait_for: path={{ headless.log_file }} search_regex="{{ headless.log_file_regex }}"
