---
## packages.yml
- name: copy the API Gateway RPMs
  copy: src={{ item.src }} dest={{ item.dest }} owner={{ ssg_packages.owner }} group={{ ssg_packages.group }} mode=644
  with_items:
  ## These must be in this order since Ansible cannot determine local RPM dependencies
  - "{{ ssg_packages.gateway }}"
  - "{{ ssg_packages.appliance }}"
  - "{{ ssg_packages.platform }}"

- name: install the API Gateway RPMs
  yum: name={{item}} state=installed
  with_items:
  ## These must be in this order since Ansible cannot determine local RPM dependencies
  - "{{ ssg_packages.gateway.dest }}"
  - "{{ ssg_packages.appliance.dest }}"
  - "{{ ssg_packages.platform.dest }}"

- name: ensure ssg is running and starts on boot
  service: name=ssg state=started enabled=true
  when: ssg_packages.platform is defined

