---
## database.yml
# Need to do this for idempotency, see
# 'localhost' needs to be the last item for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user

- debug: msg="ansible_hostname, inventory_hostname, database.host - {{ ansible_hostname }}, {{inventory_hostname}}, {{ database.host }}"

- name: Set the login_host to "localhost" if {{ database.host }} == {{ inventory_hostname }}
  set_fact:
    login_host: "localhost"
  when: "'{{database.host}}' == '{{inventory_hostname}}'"

- name: Set the login_host to {{ database.host }} if {{ database.host }} != {{ inventory_hostname }}
  set_fact:
    login_host: "{{ database.host }}"
  when: "'{{database.host}}' != '{{inventory_hostname}}'"

- name: update mysql root password for all root accounts
  mysql_user: name={{ database.admin.user }}
            host={{ item }}
            priv=*.*:ALL,GRANT
            password={{ database.admin.pass }}
            login_host={{ login_host }}
            login_port={{ database.port }}
  with_items:
    - 127.0.0.1
    - ::1
    - "%"
    - localhost

- name: copy .my.cnf file with root password credentials
  template: src=roles/mysql/templates/my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: ensure anonymous users are not in the database
  mysql_user: name=''
            host={{ item }}
            state=absent
            login_host={{ login_host }}
            login_port={{ database.port }}
  with_items:
    - 127.0.0.1
    - ::1
    - "%"
    - localhost

- name: remove the test database
  mysql_db: name=test
          state=absent
          login_host={{ login_host }}
          login_port={{ database.port }}
