---
## packages.yml
- name: unzip the {{ otk_sk.file.src }} for OTK solution kit RESTman installation
  unarchive: src={{ otk_sk.file.src }} dest={{ otk_sk.file.dest }} mode=644
  environment:
    LANG: C
    LC_ALL: C
    LC_MESSAGES: C

- name: Replace the "<?YOUR_SSG>?" regex with the "https://{{ cluster.host }}:{{ cluster.ssl_port }}"
  replace: 'dest={{ item.dest }} regexp="<?YOUR_SSG>?" replace="https://{{ cluster.host }}:{{ cluster.ssl_port }}" backup=yes'
  with_items:
    - "{{ otk_database_files.sql.otk_db_testdata }}"
    - "{{ otk_database_files.cql.otk_db_testdata }}"
