---
## set restman max size cluster property
- name:
  set_fact:
    cluster_property_command: "/usr/bin/curl -u {{ admin.user }}:{{ admin.pass }} -X GET -k -H 'Content-Type: application/xml' -s -D - https://localhost:{{ cluster_property.ssl_port }}{{ cluster_property.api_url }}?name={{ cluster_property.name1 }} | grep '{{ cluster_property.id_xml_tag }}' | sed -e '{{ cluster_property.id_regex }}'"

- name: check if the restman cluster property exists
  shell: "{{cluster_property_command}}"
  register: cluster_property_id
- debug: msg="{{cluster_property_id.stdout}}"

- name: copy the {{ cluster_property.file.src }} to the appropriate destination
  template: src={{ cluster_property.file.src }} dest={{ cluster_property.file.dest }} mode=644
  when: cluster_property_id != ""

- name: post a new property
  command: "/usr/bin/curl -u {{ admin.user }}:{{ admin.pass }} -X POST -k -H 'Content-Type: application/xml' -d @{{ cluster_property.file.dest }} -s -D - https://localhost:{{ cluster_property.ssl_port }}{{ cluster_property.api_url }} -o {{ cluster_property.curl_log }}"
  when: cluster_property_id != ""

- name: capture the restman maxsize property ID
  shell: "{{cluster_property_command}}"
  register: cluster_property_id
  when: cluster_property_id != ""

- debug: msg="{{cluster_property_id.stdout}}"