---
## database.yml
- name: set the fact
  set_fact:
    create_statement: "CREATE KEYSPACE IF NOT EXISTS {{ otk_database.schema }} WITH replication = {'class' : 'SimpleStrategy', 'replication_factor' : 1};"

- name: create the OTK Cassandra database and seed test data
  command: "/usr/bin/cqlsh -u {{ otk_database.admin.user }} -p {{ otk_database.admin.pass }} --cqlversion='3.2.1' {{ otk_database.host }} {{ otk_database.port }} -e \"{{ create_statement }}\" >> /var/tmp/install_otk_otk_database.sql.log 2>&1"
  when: otk_database.technology is defined and otk_database.technology == "cassandra"

- name: create the OTK Cassandra database and seed test data
  command: "/usr/bin/cqlsh -u {{ otk_database.admin.user }} -p {{ otk_database.admin.pass }} --cqlversion='3.2.1' {{ otk_database.host }} {{ otk_database.port }} -k {{ otk_database.schema }} -f {{ item.dest }} >> /var/tmp/install_otk_otk_database.sql.log 2>&1"
  with_items:
    - "{{ otk_database_files.cql.otk_db_schema }}"
    - "{{ otk_database_files.cql.otk_db_testdata }}"
  when: otk_database.technology is defined and otk_database.technology == "cassandra"
