---
## database.yml
- name: create the OTK MySQL database schema
  mysql_db: name={{ otk_database.schema }}
          state=present
          login_host={{ login_host }}
          login_port={{ otk_database.port }}
          login_user={{ otk_database.admin.user }}
          login_password={{ otk_database.admin.pass }}

- name: create the OTK user
  mysql_user: name={{ otk_database.user }}
            host={{ item }}
            priv={{ otk_database.schema }}.*:ALL
            password={{ otk_database.pass }}
            login_host={{ login_host }}
            login_port={{ otk_database.port }}
            login_user={{ otk_database.admin.user }}
            login_password={{ otk_database.admin.pass }}
  with_items:
    - 127.0.0.1
    - ::1
    - "%"
    - localhost

- name: create the OTK MySQL database and seed test data
  mysql_db: name={{ otk_database.schema }}
          state=import
          target={{ item.dest }}
          login_host={{ login_host }}
          login_port={{ otk_database.port }}
          login_user={{ otk_database.admin.user }}
          login_password={{ otk_database.admin.pass }}
  with_items:
    - "{{ otk_database_files.sql.otk_db_schema }}"
    - "{{ otk_database_files.sql.otk_db_testdata }}"
