---
## the main.yml includes all the components for the role
- include: packages.yml

## Need to set the login_host if localhost
- name: Set the login_host to "localhost" if {{ mag_database.host }} == {{ inventory_hostname }}
  set_fact:
    login_host: "localhost"
  when: "'{{mag_database.host}}' == '{{inventory_hostname}}'"

- name: Set the login_host to {{ mag_database.host }} if {{ mag_database.host }} != {{ inventory_hostname }}
  set_fact:
    login_host: "{{ mag_database.host }}"
  when: "'{{mag_database.host}}' != '{{inventory_hostname}}'"

- debug: msg="login_host = {{login_host}}, mag_database.port = {{mag_database.port}}, mag_database.technology = {{mag_database.technology}}"

- include: cassandra_database.yml
  when: mag_database.technology is defined and mag_database.technology == "cassandra"
- include: mysql_database.yml
  when: mag_database.technology is not defined or mag_database.technology == "mysql"
- include: mag_test_client.yml
  when: mag_database.technology is not defined or mag_database.technology == "mysql"
