---
## packages.yml
- name: Add the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Add the Amazon specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  when:
    - ansible_distribution == 'Amazon'

- name: install MySQL Server, Client, and libraries
  yum: name={{ item }} enablerepo=mysql57-community state=installed
  with_items: "{{ mysql_rpms }}"
  when: ansible_os_family == 'RedHat'

- name: ensure empty password for root at initialisation
  replace:
    name: /etc/init.d/mysqld
    regexp: '--initialize'
    replace: ' --initialize-insecure'
    
- name: Copy new my.cnf file
  copy: src="roles/mysql/files/my.cnf" dest="/etc/my.cnf" owner="root" group="root" mode=644 backup=yes

- name: ensure mysqld is running and starts on boot
  service: name=mysqld state=started enabled=true
