---
## the main.yml includes all the components for the role
- include: packages.yml

## Need to set the databases' login_host if localhost
- name: Set the login_host to "localhost" if {{ mas_identity_mas_database.host }} == {{ inventory_hostname }}
  set_fact:
    login_host: "localhost"
  when: mas_identity_mas_database.technology == "cassandra" and mas_identity_mas_database.host == inventory_hostname

- name: Set the login_host to {{ mas_identity_iip_database.host }} if {{ mas_identity_iip_database.host }} != {{ inventory_hostname }}
  set_fact:
    login_host: "{{ mas_identity_iip_database.host }}"
  when: "'{{mas_identity_iip_database.host}}' != '{{inventory_hostname}}'"

- debug: msg="login_host = {{login_host}}, mas_identity_iip_database.port = {{mas_identity_iip_database.port}}, mas_identity_iip_database.technology = {{mas_identity_iip_database.technology}}"

- include: mas_cassandra_database.yml
  when: mas_identity_mas_database.technology == "cassandra"

- include: mas_cassandra_connection.yml
  when: mas_identity_mas_database.technology == "cassandra"
## TODO
#- include: ldap_identity_provider.yml
#- include: active_directory_identity_provider.yml
#- include: internal_identity_provider.yml
- include: iip_jdbc_connection.yml
- include: solution_kits.yml
