---
- hosts: all
  vars_files:
    - group_vars/mysql.yml
    - group_vars/cassandra.yml
    - group_vars/mosquitto.yml
    - group_vars/openldap.yml
    - group_vars/gateway.yml
    - group_vars/sso.yml
    - group_vars/otk.yml
    - group_vars/mobile.yml
    - group_vars/mas.yml
    - group_vars/mas_messaging.yml
    - group_vars/mas_identity.yml
    - group_vars/mas_storage.yml
  roles:
    - common
    - mysql
    - cassandra
    - mosquitto
    - openldap
    - gateway
    - sso
    - otk
    - otk_schema_data
    - mobile
    - mobile_schema_data
    - otk_extras
    - private_key
    - mas_messaging
    - mas_identity
    - mas_storage
    - restart_services
