---
- hosts: mysql_databases
  vars_files:
    - group_vars/mysql.yml
    - group_vars/gateway.yml
    - group_vars/otk.yml
  roles:
    - mysql
- hosts: gateways
  vars_files:
    - group_vars/mysql.yml
    - group_vars/gateway.yml
    - group_vars/sso.yml
    - group_vars/otk.yml
  roles:
    - common
    - gateway
    - sso
    - otk
    - otk_schema_data
    - restart_services
