---
headless:
  owner: "layer7"
  group: "layer7"
  mode: 0644
  file:
    src: "roles/gateway/files/gateway.config.j2"
    dest: "/var/tmp/gateway.config"
  sudo:
    username: "layer7"
  log_file_regex: "Internal service Gateway REST Management Service created"
  log_file: "/opt/SecureSpan/Gateway/node/default/var/logs/ssg_0_0.log"
  sleep: 5
trusted_certificate:
  owner: "layer7"
  group: "layer7"
  ssl_port: 9443
  file:
    src: "roles/gateway/files/trusted_certificate.j2"
    dest: "/var/tmp/gateway_trusted_certificate.xml"
  api_url: "/restman/1.0/trustedCertificates"
  curl_log: "/var/tmp/restman_trusted_certificate.log"

