---
## jdbc_connection.yml
- name:
  set_fact:
    otk_variable_configuration_policy_command: "/usr/bin/curl -u {{ admin.user }}:{{ admin.pass }} -X GET -k -H 'Content-Type: application/xml' -s -D - https://localhost:{{ otk_variable_configuration_policy.ssl_port }}{{ otk_variable_configuration_policy.api_url }}?name={{ otk_variable_configuration_policy.name }} | grep '{{ otk_variable_configuration_policy.id_xml_tag }}' | sed -e '{{ otk_variable_configuration_policy.id_regex }}'"

- name: Check if the "{{ otk_variable_configuration_policy.name }}" policy exists
  shell: "{{ otk_variable_configuration_policy_command }}"
  register: otk_variable_configuration_policy_cmd

- set_fact: otk_variable_configuration_policy_id="{{ otk_variable_configuration_policy_cmd.stdout }}"
  when: otk_variable_configuration_policy_cmd.changed
- debug: msg="{{ otk_variable_configuration_policy_id }}"

- name: copy the {{ otk_variable_configuration_policy.file.src }} to the appropriate destination
  template: src={{ otk_variable_configuration_policy.file.src }} dest={{ otk_variable_configuration_policy.file.dest }} mode=644
  when: otk_variable_configuration_policy_id != ""

- name: update the "{{ otk_variable_configuration_policy.name }}" policy
  command: "/usr/bin/curl -u {{ admin.user }}:{{ admin.pass }} -X PUT -k -H 'Content-Type: application/xml' -d @{{ otk_variable_configuration_policy.file.dest }} -s -D - https://localhost:{{ otk_variable_configuration_policy.ssl_port }}{{ otk_variable_configuration_policy.api_url }}/{{ otk_variable_configuration_policy_id }} -o {{ otk_variable_configuration_policy.curl_log }}"
  when: otk_variable_configuration_policy_id != ""
