#
#  Copyright (c) 2016 CA. All rights reserved.
#
#  This software may be modified and distributed under the terms
#  of the MIT license. See the LICENSE file for details.
#
version: '2'
services:
  ssg:
    build:
      context: .
      dockerfile: Dockerfile
    mem_limit: 4g
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9443:9443"
    hostname: "mas.docker.local"
    environment:
      SSG_CLUSTER_HOST: "mas.docker.local"
      SSG_CLUSTER_PASSWORD: "7layer"
      SSG_DATABASE_JDBC_URL: "jdbc:mysql://mysqldb:3306/ssg"
      SSG_DATABASE_USER: "root"
      SSG_DATABASE_PASSWORD: "7layer"
      SSG_ADMIN_USERNAME: "admin"
      SSG_ADMIN_PASSWORD: "7layer"
      ACCEPT_LICENSE: "true"
      SSG_JVM_HEAP: "4g"
      EXTRA_JAVA_ARGS: "-XX:ParallelGCThreads=4 -Dcom.l7tech.bootstrap.env.license.enable=false -Dcom.l7tech.bootstrap.autoTrustSslKey=trustAnchor,TrustedFor.SSL,TrustedFor.SAML_ISSUER"
      # SSG_LICENSE: "your_license_here" or mounted

  mysqldb:
    image: mysql:5.7
    mem_limit: 512m
    environment:
      - MYSQL_ROOT_PASSWORD=7layer
      - MYSQL_DATABASE=ssg
      - MYSQL_USER=db_admin
      - MYSQL_PASSWORD=7layer
    command:
      - "--character-set-server=utf8"
      - "--innodb_log_buffer_size=32M"
      - "--innodb_log_file_size=80M"
      - "--max_allowed_packet=8M"
    # volumes:
    #   - ./files/mysql/:/docker-entrypoint-initdb.d/
    