---
## packages.yml
- name: install Portal RPM - This is custom install and not fully supported by CA yet...
  yum: name={{ rpms.portal }} state=present

- name: copy the base package - This is custom install and not fully supported by CA yet...
  copy: src={{ baseX.file.src }} dest={{ baseX.file.dest }} mode=655 backup=yes

- name: copy the setup_script - This is custom install and not fully supported by CA yet...
  copy: src={{ setup_script.file.src }} dest={{ setup_script.file.dest }} mode=755 backup=yes
