---
msso_config_service:
  name: "msso_config_service"
  url: "/msso_config"
  args: "client_id=ae4e29c2-1a95-4956-84b4-c8a8b88c9834" # DemoApp
  owner: "layer7"
  group: "layer7"
  ssl_port: 9443
  file:
    src: "roles/msso_config/files/msso_config_service.j2"
    dest: '/var/tmp/msso_config_service.xml'
  api_url: '/restman/1.0/services'
  id_xml_tag: 'l7:Id'
  id_regex: 's,.*<l7:Id>\([^<]*\)</l7:Id>.*,\1,g'
  curl_log: '/var/tmp/restman_msso_config_service.log'
