---
otk_variable_configuration_policy:
  name: "OTK%20Variable%20Configuration"
  owner: "layer7"
  group: "layer7"
  ssl_port: 9443
  file:
    src: "roles/otk_extras/files/otk_variable_configuration_policy.j2"
    dest: '/var/tmp/otk_variable_configuration_policy.xml'
  api_url: '/restman/1.0/policies'
  id_xml_tag: 'l7:Id'
  id_regex: 's,.*<l7:Id>\([^<]*\)</l7:Id>.*,\1,g'
  curl_log: '/var/tmp/restman_otk_variable_configuration_policy.log'
otk_authorization_server_configuration_policy:
  name: "OTK%20Authorization%20Server%20Configuration"
  owner: "layer7"
  group: "layer7"
  ssl_port: 9443
  file:
    src: "roles/otk_extras/files/otk_authorization_server_configuration_policy.j2"
    dest: '/var/tmp/otk_authorization_server_configuration_policy.xml'
  api_url: '/restman/1.0/policies'
  id_xml_tag: 'l7:Id'
  id_regex: 's,.*<l7:Id>\([^<]*\)</l7:Id>.*,\1,g'
  curl_log: '/var/tmp/restman_otk_authorization_server_configuration_policy.log'
