---
## jdbc_connection.yml
- name:
  set_fact:
    iip_jdbc_connection_command: "/usr/bin/curl -u {{ admin.user }}:{{ admin.pass }} -X GET -k -H 'Content-Type: application/xml' -s -D - https://localhost:{{ iip_jdbc_connection.ssl_port }}{{ iip_jdbc_connection.api_url }}?name={{ iip_jdbc_connection.name }} | grep '{{ iip_jdbc_connection.id_xml_tag }}' | sed -e '{{ iip_jdbc_connection.id_regex }}'"

- name: Check if the MAS Identity JDBC Connection exists
  shell: "{{ iip_jdbc_connection_command }}"
  register: iip_jdbc_connection_id
- debug: msg="{{ iip_jdbc_connection_id.stdout }}"

- name: copy the {{  iip_jdbc_connection.file.src }} to the appropriate destination
  template: src={{  iip_jdbc_connection.file.src }} dest={{  iip_jdbc_connection.file.dest }} mode=644
  when:  iip_jdbc_connection_id != ""

- name: create the MAS Identity JDBC connection
  command: "/usr/bin/curl -u {{ admin.user }}:{{ admin.pass }} -X POST -k -H 'Content-Type: application/xml' -d @{{  iip_jdbc_connection.file.dest }} -s -D - https://localhost:{{  iip_jdbc_connection.ssl_port }}{{  iip_jdbc_connection.api_url }} -o {{  iip_jdbc_connection.curl_log }}"
  when:  iip_jdbc_connection_id != ""

- name: capture the MAS Identity JDBC connection ID
  shell: "{{ iip_jdbc_connection_command }}"
  register:  iip_jdbc_connection_id
  when:  iip_jdbc_connection_id != ""

- debug: msg="{{ iip_jdbc_connection_id.stdout }}"
