---
## database.yml
## Need to create the MAS Identity IIP user to query the local SSG user store
- name: create the MAS Identity IIP user
  mysql_user: name={{ mag_database.user }}
            host={{ item }}
            priv={{ mas_identity_iip_database.schema }}.*:ALL
            password={{ mas_identity_iip_database.pass }}
            login_host={{ login_host }}
            login_port={{ mas_identity_iip_database.port }}
            login_user={{ mas_identity_iip_database.admin.user }}
            login_password={{ mas_identity_iip_database.admin.pass }}
  with_items:
    - 127.0.0.1
    - ::1
    - "%"
    - localhost
