---
## packages.yml
## packages.yml
- name: Add the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Add the Amazon specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  when:
    - ansible_distribution == 'Amazon'

- name: install MySQL Client, and libraries
  yum: name={{ item }} enablerepo=mysql57-community state=installed
  with_items: "{{ mysql_rpms }}"
  when: ansible_os_family == 'RedHat'
