####################################################################################
#
# Modified by Aric Day (aric.day@broadcom.com) - August 2019
#
####################################################################################
version: '3.7'
services:
  api-gateway:
    image: caapim/gateway
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9443:9443"
    volumes:
      - /opt/SecureSpan/Gateway/node/default/etc/bootstrap/services/restman
      - ./license:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/license
    environment:
      ACCEPT_LICENSE: "true"
      SSG_ADMIN_USERNAME: "admin"
      SSG_ADMIN_PASSWORD: "7layer"
