####################################################################################
#
# Modified by Aric Day (aric.day@broadcom.com) - Jan 2020
#
####################################################################################
version: '3.7'
services:
  # hazelcast imdg (cluster server)
  hazelcast:
    image: hazelcast/hazelcast
    volumes:
        - ./hazelcast/hazelcast.xml:/configFolder/hazelcast.xml
        - ./hazelcast/hazelcast-client.xml:/configFolder/hazelcast-client.xml
    environment:
        - JAVA_OPTS=-Dhazelcast.config=/configFolder/hazelcast.xml -Dhazelcast.mancenter.url=http://mancenter:8080/hazelcast-mancenter -Dgroup.name=hz-compose -Dgroup.password=s3crEt
    ports:
        - 5701:5701
    links:
        - "management-center:mancenter"

  #management center
  management-center:
    image: hazelcast/management-center
    # persisting mancenter users db folder to local disk
    volumes:
        - ~/mancenter3.8:/mancenter-3.8
    environment:
        - MANCENTER_DATA=/mancenter-3.8
        # enable REST interface on management center
        # http://docs.hazelcast.org/docs/latest-development/manual/html/Management/Clustered_REST_via_Management_Center.html
        - JAVA_OPTS=-Dhazelcast.mc.rest.enabled=true
    ports:
        - 8081:8080
