---
## the main.yml includes all the components for the role
- include: packages.yml

## Need to set the databases' login_host if localhost
- name: Set the login_host to "localhost" if {{ otk_database.host }} == {{ inventory_hostname }}
  set_fact:
    login_host: "localhost"
  when: "'{{otk_database.host}}' == '{{inventory_hostname}}'"

- name: Set the login_host to {{ otk_database.host }} if {{ otk_database.host }} != {{ inventory_hostname }}
  set_fact:
    login_host: "{{ otk_database.host }}"
  when: "'{{otk_database.host}}' != '{{inventory_hostname}}'"

- debug: msg="login_host = {{login_host}}, otk_database.port = {{otk_database.port}}, otk_database.technology = {{otk_database.technology}}"

- include: cassandra_connection.yml

## Dummy JDBC connection is still required to be added to the OTK SK even if Cassandra is used
- include: jdbc_connection.yml

- include: solution_kits.yml
