---
- hosts: all
  vars_files:
    - group_vars/mysql.yml
    - group_vars/gateway.yml
    - group_vars/otk.yml
    - group_vars/sso.yml
  roles:
    - common
    - mysql
    - gateway
    - sso
    - otk
    - otk_schema_data
    - restart_services
