---
- hosts: gateways
  vars_files:
    - group_vars/mysql.yml
    - group_vars/cassandra.yml
    - group_vars/mosquitto.yml
    - group_vars/openldap.yml
    - group_vars/gateway.yml
    - group_vars/otk.yml
    - group_vars/mobile.yml
    - group_vars/mas.yml
    - group_vars/mas_messaging.yml
  roles:
    - mas_messaging
    - restart_services
