---
## Note this file is only stored for demo purposes. Any production credentials should not
## be included in version control.
mobile_license:
  owner: "layer7"
  group: "root"
  file:
    src: "/Users/AricDay/API/apim_vagrant_ansible_files/SSG_MAG_9.xml"
    dest: "/opt/SecureSpan/Gateway/node/default/etc/bootstrap/license/SSG_MAG_9.xml"
mag_sk:
  owner: "layer7"
  group: "root"
  ssl_port: 9443
  file:
    src: "/Users/AricDay/API/apim_vagrant_ansible_files/MAG_Installers_4.1.00-2591.zip"
    dest: "/var/tmp/"
  sskar_file:
    dest: '/var/tmp/MAG_Installers_4.1.00-2591/MAGSolutionKit-4.1.00-2591.sskar'
  api_url: '/restman/1.0/solutionKitManagers'
mag_database:
  technology: "mysql"
  #technology: "cassandra"
  schema: "otk"
  user: "otk_user"
  pass: "7layer"
  host: "localhost"
  port: 3306
  #port: 9042
  admin:
    user: "root"
    pass: "7layer"
mag_database_files:
  owner: "layer7"
  group: "root"
  sql:
    mag_db_schema:
      dest: "/var/tmp/MAG_Installers_4.1.00-2591/Database_scripts/mysql/mag_db_schema.sql"
    mag_db_testdata:
      dest: "/var/tmp/MAG_Installers_4.1.00-2591/Database_scripts/mysql/mag_db_testdata.sql"
    mag_otk_db_data:
      dest: "/var/tmp/MAG_Installers_4.1.00-2591/Database_scripts/mysql/mag_otk_db_data.sql"
    mag_otk_db_testdata:
      dest: "/var/tmp/MAG_Installers_4.1.00-2591/Database_scripts/mysql/mag_otk_db_testdata.sql"
    mag_oauth_demoapp:
      dest: "/var/tmp/MAG_Installers_4.1.00-2591/Database_scripts/mysql/oauth_register_demoapp.sql"
    mag_test_client:
      src: "roles/mobile/files/mag_test_client.sql"
      dest: "/var/tmp/mag_test_client.sql"
  cql:
    mag_db_schema:
      dest: "/var/tmp/MAG_Installers_4.1.00-2591/Database_scripts/cassandra/mag_db_schema_cassandra.cql"
    mag_db_testdata:
      dest: "/var/tmp/MAG_Installers_4.1.00-2591/Database_scripts/cassandra/mag_db_testdata_cassandra.cql"
    mag_otk_db_data:
      dest: "/var/tmp/MAG_Installers_4.1.00-2591/Database_scripts/cassandra/mag_otk_db_data_cassandra.cql"
    mag_otk_db_testdata:
      dest: "/var/tmp/MAG_Installers_4.1.00-2591/Database_scripts/cassandra/mag_otk_db_testdata_cassandra.cql"
