---
## the main.yml includes all the components for the role
- include: packages.yml

## Need to set the databases' login_host if localhost
- name: Set the login_host to "localhost" if {{ mas_storage_database.host }} == {{ inventory_hostname }}
  set_fact:
    login_host: "localhost"
  when: "'{{mas_storage_database.host}}' == '{{inventory_hostname}}'"

- name: Set the login_host to {{ mas_storage_database.host }} if {{ mas_storage_database.host }} != {{ inventory_hostname }}
  set_fact:
    login_host: "{{ mas_storage_database.host }}"
  when: "'{{mas_storage_database.host}}' != '{{inventory_hostname}}'"

- debug: msg="login_host = {{login_host}}, mas_storage_database.port = {{mas_storage_database.port}}, mas_storage_database.technology = {{mas_storage_database.technology}}"

- include: cassandra_database.yml
  when: mas_storage_database.technology == "cassandra"

- include: cassandra_connection.yml
  when: mas_storage_database.technology == "cassandra"
- include: solution_kits.yml
