---
## mag_test_client.yml
## database and user credentials
- name: Copy the MAG Test Client data
  copy: src={{ mag_database_files.sql.mag_test_client.src }} dest={{ mag_database_files.sql.mag_test_client.dest }} owner={{ mag_database_files.owner }} group={{ mag_database_files.group }} mode=644

- name: seed the MAG Test Client data
  mysql_db: name={{ mag_database.schema }}
          state=import
          target={{ item.dest }}
          login_host={{ login_host }}
          login_port={{ mag_database.port }}
          login_user={{ mag_database.admin.user }}
          login_password={{ mag_database.admin.pass }}
  with_items:
    - "{{ mag_database_files.sql.mag_test_client }}"
